version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: sdf_redis
    ports:
      - "6379:6379"

  backend-api:
    build: ./backend
    container_name: sdf_api
    ports:
      - "8000:8000"
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
      - ./data_output:/app/data_output
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  backend-worker:
    build: ./backend
    container_name: sdf_worker
    command: python worker.py
    volumes:
      - ./backend:/app
      - ./data_output:/app/data_output
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    image: nginx:alpine
    container_name: sdf_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-api